stages:
  - 🔖 app-version
  - 🏗️ build
  - 🚀 deploy

.app_version:
  script:
    - APP_VERSION="1.${CI_COMMIT_SHORT_SHA}"
    - echo "APP_VERSION=$APP_VERSION" > app_version.env
    - echo $APP_VERSION > app_version
  artifacts:
    reports:
      dotenv: app_version.env
    paths:
      - app_version
  dependencies: []

.image_names:
  variables:
    IMAGE_NAMESPACE: focusboard
    IMAGE_REPO: focus
    IMAGE_NAME: ${IMAGE_NAMESPACE}/${IMAGE_REPO}
    HARBOR_IMAGE: $HARBOR_IMAGE_PREFIX/$IMAGE_NAME
    ECR_IMAGE: $ECR_REGISTRY/$IMAGE_NAME

.maven_cache:
  cache:
    key: maven-${CI_PROJECT_ID}
    paths:
      - .m2/repository

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  QUARKUS_PROFILE: prod

set-app-version:
  stage: 🔖 app-version
  extends: .app_version
  image: alpine:latest

build-image-jib:
  stage: 🏗️ build
  extends:
    - .image_names
    - .maven_cache
  needs:
    - set-app-version
  image: maven:3.9-eclipse-temurin-21
  variables:
    QUARKUS_CONTAINER_IMAGE_BUILD: "true"
    QUARKUS_CONTAINER_IMAGE_PUSH: "true"
    QUARKUS_CONTAINER_IMAGE_IMAGE: "$HARBOR_IMAGE:$APP_VERSION"
    QUARKUS_CONTAINER_IMAGE_ADDITIONAL_TAGS: "latest"
    QUARKUS_CONTAINER_IMAGE_REGISTRY: "$HARBOR_URL"
    QUARKUS_CONTAINER_IMAGE_USERNAME: "$HARBOR_ROBOT_NAME"
    QUARKUS_CONTAINER_IMAGE_PASSWORD: "$HARBOR_ROBOT_TOKEN"
  script:
    - ./mvnw clean package -DskipTests -Dquarkus.package.jar.type=uber-jar

push-image-ecr:
  stage: 🏗️ build
  extends: .image_names
  needs:
    - set-app-version
    - build-image-jib
  image: alpine:latest
  variables:
    AWS_REGION: eu-central-1
  before_script:
    - apk add --no-cache skopeo aws-cli
    - aws ecr describe-repositories --repository-names "$IMAGE_NAME" --region "$AWS_REGION" || aws ecr create-repository --repository-name "$IMAGE_NAME" --region "$AWS_REGION"
    - ECR_PASSWORD="$(aws ecr get-login-password --region "$AWS_REGION")"
  script:
    - skopeo copy --src-creds "$HARBOR_ROBOT_NAME:$HARBOR_ROBOT_TOKEN" --dest-creds "AWS:$ECR_PASSWORD" "docker://$HARBOR_IMAGE:$APP_VERSION" "docker://$ECR_IMAGE:$APP_VERSION"
    - skopeo copy --src-creds "$HARBOR_ROBOT_NAME:$HARBOR_ROBOT_TOKEN" --dest-creds "AWS:$ECR_PASSWORD" "docker://$HARBOR_IMAGE:latest" "docker://$ECR_IMAGE:latest"

deploy-eks-prod:
  stage: 🚀 deploy
  extends: .image_names
  needs:
    - push-image-ecr
  image:
    name: alpine/helm:4.0.5
    entrypoint: [""]
  before_script:
    - apk add aws-cli
    - aws eks update-kubeconfig --region eu-central-1 --name cnd-prod-eks
  script:
    - helm upgrade auth ./helm --namespace focus