{{- if .Values.focus.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.focus.name }}-ingress"
  namespace: focus
  annotations:
    {{- range $key, $value := .Values.focus.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.focus.ingress.className }}
  rules:
    {{- if .Values.focus.ingress.host }}
    - host: {{ .Values.focus.ingress.host }}
      http:
    {{- else }}
    - http:
    {{- end }}
        paths:
          - path: {{ .Values.focus.ingress.path }}
            pathType: {{ .Values.focus.ingress.pathType }}
            backend:
              service:
                name: "{{ .Values.focus.name }}-service"
                port:
                  number: {{ .Values.focus.service.port }}
{{- end }}