apiVersion: v1
kind: Secret
metadata:
  name: focus-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    app: focus
type: Opaque
stringData:
  QUARKUS_DATASOURCE_USERNAME: <POSTGRES_USERNAME>
  QUARKUS_DATASOURCE_PASSWORD: <POSTGRES_PASSWORD>
  DB_PASSWORD: <POSTGRES_PASSWORD>