apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.focus.serviceAccount.name }}
  namespace: {{ .Values.global.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.focus.serviceAccount.roleArn }}