quarkus:
  http:
    port: 8088

  hibernate-orm:
    enabled: true
    schema-management:
      strategy: validate
    log:
      sql: true
    packages: de.thi.focus.frameworksdrivers.persistence.jpa

  flyway:
    migrate-at-start: true
    locations: db/migration

  datasource:
    db-kind: postgresql
    username: focus
    password: focus
    jdbc:
      url: jdbc:postgresql://localhost:5432/focus

focus:
  constraints:
    note:
      max-length: 1000
    category:
      name:
        max-length: 50
  defaults:
    category-color: "#FFFFFF"
