apiVersion: v1
kind: Secret
metadata:
  name: focus-secrets
  labels:
    app: focus
type: Opaque
stringData:
  QUARKUS_DATASOURCE_USERNAME: <POSTGRES_USERNAME>
  QUARKUS_DATASOURCE_PASSWORD: <POSTGRES_PASSWORD>