# -------------------------
# Focus application
# -------------------------
focus:
  name: focus

  # Container image settings
  image:
    repository: 758280076486.dkr.ecr.eu-central-1.amazonaws.com/focusboard/focus
    tag: latest

  # Deployment configuration
  port: 8088
  replicas: 2

  # ServiceAccount (IRSA)
  serviceAccount:
    name: eks-service-account
    roleArn: "arn:aws:iam::758280076486:role/eks-auth-ecr-access-role"

  # Probes
  probes:
    liveness:
      # /healthz
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 2
      failureThreshold: 3
    readiness:
      # /readyz
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 2
      failureThreshold: 3

  # Resources
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  # HPA
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 75
    behavior:
      scaleUp:
        stabilizationWindowSeconds: 0
        selectPolicy: Max
        policies:
          percent:
            value: 100
            periodSeconds: 60
          pods:
            value: 4
            periodSeconds: 60
      scaleDown:
        stabilizationWindowSeconds: 300
        selectPolicy: Max
        policies:
          percent:
            value: 50
            periodSeconds: 60

  # Service settings
  service:
    port: 80
    type: ClusterIP

  # Ingress settings
  ingress:
    enabled: true
    className: alb
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
      alb.ingress.kubernetes.io/healthcheck-path: /q/health/live
      alb.ingress.kubernetes.io/healthcheck-interval-seconds: '30'
      alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
      alb.ingress.kubernetes.io/healthy-threshold-count: '2'
      alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
      alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:eu-central-1:758280076486:certificate/946198a1-757c-4868-8e17-e2446087313f"
      # alb.ingress.kubernetes.io/group.name: shared-alb  # Share ALB with other services
    host: ""  # = Domain name
    path: "/"
    pathType: Prefix

# -------------------------
# Quarkus env
# -------------------------
quarkus:
  http:
    port: 8088
    cors:
      enabled: true
      origins: "https://k8s-frontend-frontend-fe6f13f88d-1209588435.eu-central-1.elb.amazonaws.com,k8s-auth-authingr-e5aa653333-252007710.eu-central-1.elb.amazonaws.com"
      methods: "GET,PUT,POST,DELETE,OPTIONS"
      headers: "origin, content-type, accept, authorization"
      accessControlAllowCredentials: true

  grpc:
    clients:
      auth:
        host: auth-service.auth.svc.cluster.local
        port: 50051
        plainText: true
        useQuarkusGrpcClient: true

  hibernateOrm:
    enabled: true
    schemaManagement:
      strategy: validate
    log:
      sql: true
    packages: "de.thi.focus.frameworksdrivers.persistence.jpa"

  flyway:
    migrateAtStart: true
    locations: "db/migration"

  datasource:
    dbKind: postgresql
    jdbc:
      url: "jdbc:postgresql://postgres:5432/focus"

# Application specific configuration
focusApp:
  security:
    secureCookies: false
  constraints:
    note:
      maxLength: 1000
    category:
      name:
        maxLength: 50
  defaults:
    categoryColor: "#FFFFFF"

# -------------------------
# Postgres
# -------------------------
postgres:
  serviceName: postgres

  image:
    repository: postgres
    tag: "16-alpine"

  port: 5432
  database: focus
  user: focus
  persistence:
    enabled: true
    claimName: db-pv-claim
    storageClassName: ebs-sc
    size: 1Gi
